module.exports = {
    doc1: [
        {
            type: 'autogenerated',
            dirName: 'doc1'
        }
    ],
    doc2: [
        {
            type: 'autogenerated',
            dirName: 'doc2'
        }
    ]
}
